language: node_js
node_js:
  - 10
  - 12
  - 14

addons:
  chrome: stable
env:
  global:
    CC_TEST_REPORTER_ID=8cab02d4909f1c39d9ac896a0dea1a36b443d4db773cb8c5197914d20fd11622

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - npm install
  - npm install -g eslint

script:
  - npm run build
  - npm run test:unit

after_script:
  - cat ./test/coverage/lcov.info | coveralls
  - ./cc-test-reporter format-coverage -t lcov ./test/coverage/lcov.info
  - ./cc-test-reporter upload-coverage